### ISSUE TITLE
Ошибка на пустой базе

### ISSUE THREAD

**Issue by dis-aster** [Prototype-X/blacklist-rkn-tool#4]
Похоже, что не полная инициализация базы. На пустой базе вылетает эксепшн при попытке чтения Dump.get(Dump.param == 'webServiceVersion').value:
````
python3 bl-rkn.py --dump
Traceback (most recent call last):
  File "/home/maxim/.pyenv/versions/3.5.2/lib/python3.5/site-packages/peewee.py", line 3097, in get
    return next(clone.execute())
  File "/home/maxim/.pyenv/versions/3.5.2/lib/python3.5/site-packages/peewee.py", line 2271, in next
    obj = self.iterate()
  File "/home/maxim/.pyenv/versions/3.5.2/lib/python3.5/site-packages/peewee.py", line 2253, in iterate
    raise StopIteration
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bl-rkn.py", line 631, in <module>
    main()
  File "bl-rkn.py", line 627, in main
    BlrknCLI()
  File "bl-rkn.py", line 561, in __init__
    self._get_dump()
  File "bl-rkn.py", line 569, in _get_dump
    srv_msg = self.dump.check_service_upd()
  File "/home/maxim/Dropbox/Python/ver3/blacklist-rkn-tool/core.py", line 42, in check_service_upd
    Dump.get(Dump.param == 'webServiceVersion').value,
  File "/home/maxim/.pyenv/versions/3.5.2/lib/python3.5/site-packages/peewee.py", line 4795, in get
    return sq.get()
  File "/home/maxim/.pyenv/versions/3.5.2/lib/python3.5/site-packages/peewee.py", line 3101, in get
    % self.sql())
db.DumpDoesNotExist: Instance matching query does not exist:
SQL: SELECT `t1`.`param`, `t1`.`value` FROM `dump` AS t1 WHERE (`t1`.`param` = %s)
PARAMS: ['webServiceVersion']

**Comment by Prototype-X** [comment]
MySQL больше не поддерживается
